/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    FrontBanner: typeof import('./src/components/FrontBanner.vue')['default']
    FrontFooter: typeof import('./src/components/FrontFooter.vue')['default']
    FrontNavbar: typeof import('./src/components/FrontNavbar.vue')['default']
    FrontPrice: typeof import('./src/components/FrontPrice.vue')['default']
    FrontStrength: typeof import('./src/components/FrontStrength.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SplitButton: typeof import('primevue/splitbutton')['default']
  }
}
